-- =====================================================================
-- Buku Tamu Digital — Event Active Period (Batch)
-- Adds a minimal "active period" concept for the Dashboard "Acara Terbaru"
-- section.
--
-- Model:
--   periodes          -> one period/batch holds up to 4 events shown on
--                        the Dashboard.
--   events.periode_id -> nullable FK; NULL = legacy/old-period event (stays
--                        fully available in "Kelola Acara", hidden from the
--                        Dashboard preview).
--
-- Deterministic rule (no date heuristics):
--   A new event joins the latest period while it has fewer than 4 events;
--   otherwise a new period is started.
--
-- Non-destructive: purely additive table + column. Existing events, guests,
-- attendance, CRUD, scanner, auth, and routing are untouched.
-- Idempotent: safe to re-run.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. PERIODES
-- ---------------------------------------------------------------------
create table if not exists public.periodes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.periodes enable row level security;

-- ---------------------------------------------------------------------
-- 2. EVENTS.periode_id
-- ---------------------------------------------------------------------
alter table public.events
  add column if not exists periode_id bigint references public.periodes(id) on delete set null;

create index if not exists idx_events_periode on public.events(periode_id);

-- ---------------------------------------------------------------------
-- 3. RLS (mirror the events policies)
--    authenticated -> read (admin + panitia)
--    anon          -> read (public event preview)
--    admin         -> insert (new period started on event creation)
-- ---------------------------------------------------------------------
drop policy if exists "Authenticated can read periodes" on public.periodes;
create policy "Authenticated can read periodes"
  on public.periodes for select
  to authenticated
  using (true);

drop policy if exists "Public can read periodes" on public.periodes;
create policy "Public can read periodes"
  on public.periodes for select
  to anon
  using (true);

drop policy if exists "Admin can insert periodes" on public.periodes;
create policy "Admin can insert periodes"
  on public.periodes for insert
  to authenticated
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );