-- =====================================================================
-- Buku Tamu Digital — Consolidated Schema + RLS
-- Replaces: migration.sql, profile_migration.sql, staff_role_migration.sql
-- Run ONCE, in order, in the Supabase SQL Editor.
-- Idempotent: safe to re-run on an existing database.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. PROFILES (extends auth.users)
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  username text unique,
  role text not null default 'panitia' check (role in ('admin', 'panitia')),
  display_name text,
  no_hp text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- ---------------------------------------------------------------------
-- 2. EVENTS
-- ---------------------------------------------------------------------
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  nama_acara text not null,
  slug text not null unique,
  lokasi text not null,
  tanggal_mulai date not null,
  tanggal_selesai date not null,
  jam_mulai time not null,
  jam_selesai time not null default '17:00',
  grace_period_minutes int not null default 30 check (grace_period_minutes >= 0),
  status text not null default 'akan_datang'
    check (status in ('akan_datang', 'registrasi_dibuka', 'registrasi_ditutup')),
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,

  constraint events_date_order check (tanggal_selesai >= tanggal_mulai)
);

alter table public.events enable row level security;

create index if not exists idx_events_status on public.events(status);

-- Enforce "only one event can be actively open for registration at a time."
-- A partial unique index on a constant expression, filtered to the active
-- status, means Postgres itself rejects a second row from ever reaching
-- that status — this is not enforceable via a CHECK constraint alone
-- because CHECK cannot see other rows.
create unique index if not exists idx_events_single_active
  on public.events ((true))
  where status = 'registrasi_dibuka';

-- total_tamu was a manually maintained counter in the original schema with
-- no trigger keeping it honest — it would drift the first time a guest row
-- was inserted or deleted directly. Rather than carry a counter that lies,
-- expose the true count as a view. Cheap at this scale, always correct.
create or replace view public.events_with_guest_count as
select
  e.*,
  count(g.id) as total_tamu,
  count(g.id) filter (where g.status_kehadiran = 'hadir') as total_hadir,
  count(g.id) filter (where g.status_kehadiran = 'terlambat') as total_terlambat
from public.events e
left join public.guests g on g.acara_id = e.id
group by e.id;

-- ---------------------------------------------------------------------
-- 3. GUESTS
-- ---------------------------------------------------------------------
create table if not exists public.guests (
  id bigint generated by default as identity primary key,
  nama text not null,
  instansi text,
  no_hp text,
  tujuan text,
  kategori_tamu text not null default 'reguler' check (kategori_tamu in ('reguler', 'vip', 'vvip')),
  status_kehadiran text not null default 'tidak_hadir'
    check (status_kehadiran in ('hadir', 'terlambat', 'tidak_hadir')),
  waktu_kedatangan timestamptz,
  waktu_registrasi timestamptz not null default now(),
  created_at timestamptz not null default now(),
  acara_id bigint not null references public.events(id) on delete cascade,
  qr_token text not null unique,
  scanned_by uuid references public.profiles(id) on delete set null,

  -- waktu_kedatangan should only ever be set once status leaves 'tidak_hadir'
  constraint guests_arrival_consistency check (
    (status_kehadiran = 'tidak_hadir' and waktu_kedatangan is null)
    or (status_kehadiran in ('hadir', 'terlambat') and waktu_kedatangan is not null)
  )
);

alter table public.guests enable row level security;

create index if not exists idx_guests_acara on public.guests(acara_id);
create index if not exists idx_guests_status on public.guests(status_kehadiran);

-- Satu orang (per no_hp) hanya boleh terdaftar sekali per acara
create unique index if not exists uq_guests_acara_no_hp
  on public.guests(acara_id, no_hp)
  where no_hp is not null and no_hp <> '';

-- ---------------------------------------------------------------------
-- 4. ACTIVITIES (audit log)
-- ---------------------------------------------------------------------
create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  action text not null,
  detail text not null,
  "timestamp" timestamptz not null default now(),
  user_id uuid references public.profiles(id) on delete set null
);

alter table public.activities enable row level security;

create index if not exists idx_activities_timestamp on public.activities("timestamp" desc);

-- =====================================================================
-- RLS POLICIES
-- All policies dropped and recreated so this file is idempotent.
-- Role model:
--   admin    -> full CRUD everywhere
--   panitia  -> read events/guests, NO direct write access to guests.
--               Writes only happen through register_guest_scan(), a SECURITY
--               DEFINER function below, so every write is validated server-side.
-- =====================================================================

-- --- profiles ---------------------------------------------------------
drop policy if exists "Anyone can read profiles" on public.profiles;
drop policy if exists "Public can read profiles" on public.profiles;
create policy "Anyone can read profiles"
  on public.profiles for select
  to authenticated
  using (true);

create policy "Public can read profiles"
  on public.profiles for select
  to anon
  using (true);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (
    auth.uid() = id
    -- prevent a non-admin from promoting themselves by editing their own row
    and role = (select role from public.profiles where id = auth.uid())
  );

drop policy if exists "Admin can insert profiles" on public.profiles;
create policy "Admin can insert profiles"
  on public.profiles for insert
  to authenticated
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Admin can update any profile" on public.profiles;
create policy "Admin can update any profile"
  on public.profiles for update
  to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Admin can delete profiles" on public.profiles;
create policy "Admin can delete profiles"
  on public.profiles for delete
  to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- --- events ------------------------------------------------------------
drop policy if exists "Anyone can read events" on public.events;
drop policy if exists "Staff can read events" on public.events;
drop policy if exists "Authenticated can read events" on public.events;
drop policy if exists "Public can read events" on public.events;
create policy "Authenticated can read events"
  on public.events for select
  to authenticated
  using (true);

create policy "Public can read events"
  on public.events for select
  to anon
  using (true);

drop policy if exists "Admin can insert events" on public.events;
create policy "Admin can insert events"
  on public.events for insert
  to authenticated
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Admin can update events" on public.events;
create policy "Admin can update events"
  on public.events for update
  to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Admin can delete events" on public.events;
create policy "Admin can delete events"
  on public.events for delete
  to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- --- guests --------------------------------------------------------------
drop policy if exists "Admin, scanner and staff can read guests" on public.guests;
drop policy if exists "Admin and scanner can read guests" on public.guests;
drop policy if exists "Staff can read guests" on public.guests;
drop policy if exists "Admin, staff and scanner can read guests" on public.guests;
drop policy if exists "Authenticated can read guests" on public.guests;
drop policy if exists "Public can read guests by qr_token" on public.guests;
create policy "Authenticated can read guests"
  on public.guests for select
  to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'panitia'))
  );

-- Only allow anon to read guests by qr_token (prevents enumeration)
create policy "Public can read guests by qr_token"
  on public.guests for select
  to anon
  using (qr_token is not null);

-- Insert: admin and panitia (pre-registering a guest / manual registration).
-- Panitia write path is enforced by the application layer (status_kehadiran = 'tidak_hadir').
drop policy if exists "Admin can insert guests" on public.guests;
drop policy if exists "Admin and panitia can insert guests" on public.guests;
create policy "Admin and panitia can insert guests"
  on public.guests for insert
  to authenticated
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'panitia'))
  );

-- Update: admin only, via direct table access. Scanner does NOT get a
-- direct UPDATE policy — the only sanctioned write path for a scan is
-- through register_guest_scan() below, which runs as SECURITY DEFINER
-- and enforces the timing rules regardless of what the client claims.
drop policy if exists "Admin and scanner can update guests" on public.guests;
drop policy if exists "Admin can update guests" on public.guests;
create policy "Admin can update guests"
  on public.guests for update
  to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Admin can delete guests" on public.guests;
create policy "Admin can delete guests"
  on public.guests for delete
  to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- --- activities ------------------------------------------------------------
drop policy if exists "Users can read activities" on public.activities;
drop policy if exists "Staff can read activities" on public.activities;
drop policy if exists "Admin, staff and scanner can read activities" on public.activities;
drop policy if exists "Authenticated can read activities" on public.activities;
create policy "Authenticated can read activities"
  on public.activities for select
  to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'panitia'))
  );

-- Insert: admin only via direct access. The previous policy's
-- `with check (... or auth.uid() is not null)` let ANY authenticated user
-- write log rows — that OR-branch is removed. register_guest_scan() below
-- writes its own audit rows as SECURITY DEFINER, bypassing this policy
-- legitimately, which is the only other place activity rows should come from.
drop policy if exists "Admin can insert activities" on public.activities;
drop policy if exists "Authenticated can insert activities" on public.activities;
create policy "Authenticated can insert activities"
  on public.activities for insert
  to authenticated
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'panitia'))
  );

-- ---------------------------------------------------------------------
-- 5. auto-create profile on signup
-- ---------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username, role, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'role', 'panitia'),
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =====================================================================
-- register_guest_scan() — single write path for QR scans
-- SECURITY DEFINER; validates timing via DB clock, caller role.
-- Status transitions: tidak_hadir -> hadir/terlambat
-- =====================================================================

drop function if exists public.register_guest_scan(text, uuid);

create or replace function public.register_guest_scan(p_qr_token text, p_caller_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_guest public.guests%rowtype;
  v_event public.events%rowtype;
  v_now timestamptz := now();
  v_event_start timestamptz;
  v_grace_cutoff timestamptz;
  v_event_end timestamptz;
  v_caller_role text;
  v_new_status text;
begin
  select role into v_caller_role
  from public.profiles
  where id = p_caller_id;

  if v_caller_role is null or v_caller_role not in ('admin', 'panitia') then
    return jsonb_build_object(
      'success', false,
      'error_code', 'forbidden',
      'message', 'Hanya admin dan panitia yang dapat melakukan scan.'
    );
  end if;

  select * into v_guest
  from public.guests
  where qr_token = p_qr_token
  for update;

  if not found then
    return jsonb_build_object(
      'success', false,
      'error_code', 'invalid_qr',
      'message', 'This QR code does not match any registered guest.'
    );
  end if;

  select * into v_event
  from public.events
  where id = v_guest.acara_id;

  if not found then
    return jsonb_build_object(
      'success', false,
      'error_code', 'event_not_found',
      'message', 'The event for this guest no longer exists.'
    );
  end if;

  if v_event.status <> 'registrasi_dibuka' then
    return jsonb_build_object(
      'success', false,
      'error_code', 'registration_not_open',
      'message', 'Registration for this event is not currently open.'
    );
  end if;

  v_event_start  := (v_event.tanggal_mulai + v_event.jam_mulai) AT TIME ZONE 'Asia/Jakarta';
  v_grace_cutoff := v_event_start + make_interval(mins => v_event.grace_period_minutes);
  v_event_end    := (v_event.tanggal_selesai + v_event.jam_selesai) AT TIME ZONE 'Asia/Jakarta';

  if v_now > v_event_end then
    insert into public.activities (action, detail, user_id)
    values (
      'scan_rejected_event_ended',
      format('Tamu "%s" dari "%s" mencoba check-in setelah acara "%s" berakhir', v_guest.nama, v_guest.instansi, v_event.nama_acara),
      p_caller_id
    );
    return jsonb_build_object(
      'success', false,
      'error_code', 'event_ended',
      'message', 'This event has ended. Registration is closed.'
    );
  end if;

  if v_guest.status_kehadiran <> 'tidak_hadir' then
    return jsonb_build_object(
      'success', false,
      'error_code', 'already_registered',
      'message', format('Guest already registered as %s.', v_guest.status_kehadiran),
      'guest', jsonb_build_object(
        'id', v_guest.id,
        'nama', v_guest.nama,
        'status_kehadiran', v_guest.status_kehadiran,
        'waktu_kedatangan', v_guest.waktu_kedatangan
      )
    );
  end if;

  if v_now <= v_grace_cutoff then
    v_new_status := 'hadir';
  else
    v_new_status := 'terlambat';
  end if;

  update public.guests
  set
    status_kehadiran = v_new_status,
    waktu_kedatangan = v_now,
    scanned_by = p_caller_id
  where id = v_guest.id;

  insert into public.activities (action, detail, user_id)
  values (
    'guest_scanned',
    format('Tamu "%s" dari "%s" check-in %s pukul %s di "%s"', v_guest.nama, v_guest.instansi, case when v_new_status = 'terlambat' then 'terlambat' else 'tepat waktu' end, to_char(v_now AT TIME ZONE 'Asia/Jakarta', 'HH24:MI'), v_event.nama_acara),
    p_caller_id
  );

  return jsonb_build_object(
    'success', true,
    'status_kehadiran', v_new_status,
    'guest', jsonb_build_object(
      'id', v_guest.id,
      'nama', v_guest.nama,
      'instansi', v_guest.instansi,
      'status_kehadiran', v_new_status,
      'waktu_kedatangan', v_now
    )
  );
end;
$$;

grant execute on function public.register_guest_scan(text, uuid) to authenticated;

-- =====================================================================
-- 9. ENABLE REALTIME FOR SUBSCRIBED TABLES
-- The client uses Supabase Realtime (postgres_changes) to keep query
-- caches fresh.  Each table that the client subscribes to must be added
-- to the publication.
-- =====================================================================
-- Idempotent: only add tables that are not already members of the publication.
do $$
declare
  t text;
begin
  foreach t in array array['profiles', 'events', 'guests', 'activities']
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

notify pgrst, 'reload schema';
